---
name: "Build Sphinx documentation"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build HTML
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/Source"
